# This docker-compose should be user for development purposes only.
version: "3"
services:
  web:
    image: ${DOCKER_IMAGE_NAME-salareuniao}
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [ "./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/start_rails.sh"]
    entrypoint: dev_docker_entrypoint.sh
    volumes:
      - .:/rdmapps:cached
      - global_gems_cache_ubuntu:/usr/local/bundle/gems
      - global_node_modules_cache:/rdmapps/node_modules
    tmpfs:
      - /rdmapps/tmp/pids
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      WEB_CONCURRENCY: 0
      DB_HOST: db
      DB_PASS: postgres
      DB_USER: postgres
      RAILS_MAX_THREADS: 1
      CHOKIDAR_USEPOLLING: 'true'
      REDIS_URL: redis://redis:6379/0
      WEBPACKER_DEV_SERVER_HOST: yarn
      WEBPACKER_DEV_SERVER_PORT: 3001
      WEBPACKER_DEV_SERVER_PUBLIC: yarn:3001
    tty: true
    stdin_open: true
    container_name: "web"
  yarn:
    image: ${DOCKER_IMAGE_NAME-salareuniao}
    command: "./scripts/start_webpack_dev.sh"
    volumes:
      - .:/rdmapps:cached
      - global_gems_cache_ubuntu:/usr/local/bundle/gems
      - global_node_modules_cache:/rdmapps/node_modules
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0 # Hot Reload só funciona com o 0.0.0.0
      WEBPACKER_DEV_SERVER_PORT: 3001
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3001 # Hot Reload só funciona com o 0.0.0.0
  sidekiq:
    image: ${DOCKER_IMAGE_NAME-salareuniao}
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "bundle", "exec", "sidekiq", "-c", "6", "-q", "default", "-q", "mailers", "-q", "push_notifications", "-q", "active_storage_analysis", "-q", "active_storage_purge"]
    volumes:
      - .:/rdmapps:cached
      - global_gems_cache_ubuntu:/usr/local/bundle/gems
      - global_node_modules_cache:/rdmapps/node_modules
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PASS: postgres
      DB_USER: postgres
      REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:alpine
  db:
    image: postgres:12-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
volumes:
  global_gems_cache_ubuntu:
    external:
      name: global_gems_cache_ubuntu
  global_node_modules_cache:
    external:
      name: global_node_modules_cache
  database: